### ISSUE TITLE
Selection for q k v

### ISSUE THREAD

**Issue by cyh-0** [yanghongji2007/cross_view_localization_EgoTR#1]
Hello, amazing work!

I am trying to build a cross-attention module, in my implementation, I use Key and Value from one view and Query from another (ps. I saw some people saying that the source for Key and Value should always be the same), but I notice that in your paper, you actually use Query and Value from the same source, just wondering why this is the case? Have you guys tried for example use Query for x_{l-1} and Key and Value from x_{l-2}?

Looking forward to hearing from you
Cheers

**Comment by yanghongji2007** [comment]
Hi, Chikara!

This question is interesting! I think it should be fine. The Query and Key are computed to get attention score and then attach to Value. So we try to keep Value always from x_{l-1}. And I don't agree that "the source for Key and Value should always be the same", is there any work support for this point? I notice that some works (e.g. https://arxiv.org/abs/2110.06821) that using Value and attn score from different sources.

**Comment by cyh-0** [comment]
Thanks for your response, as far as I know, the original transformer (decoder part) use queries from the previous decoder layer and keys and values from the output of the encoder.
